pub mod adapters;
pub mod agents;
#[cfg(feature = "bench")]
pub mod bench_corpus;
pub mod bus;
pub mod commands;
pub mod events;
pub mod font_config;
pub mod git_branches;
pub mod git_graph;
pub mod git_info;
pub mod git_pr;
pub mod git_util;
pub mod git_worktrees;
pub mod history;
pub mod input;
pub mod peer;
#[cfg(feature = "bench")]
pub mod perf_registry;
pub mod protocol;
pub mod render_sync;
#[cfg(feature = "bench")]
pub mod runtime_modes;
pub mod terminal;
pub mod worktree_prep;
